### ISSUE TITLE
Watch multiple destinations

### ISSUE THREAD

**Issue by chrisjaure** [jmreidy/grunt-browserify#199] opened 2014-05-30 18:03 UTC
I'm trying to build bundles with dynamic mappings but it doesn't appear to be working.

For example, instead of specifying `src` and `dest`, I'm using a dynamic mapping like this:
```
files: [
        {
          expand: true,     // Enable dynamic expansion.
          cwd: 'lib/',      // Src matches are relative to this path.
          src: ['**/*.app.js'], // Actual pattern(s) to match.
          dest: 'build/',   // Destination path prefix.
          ext: '.min.js',   // Dest filepaths will have this extension.
          extDot: 'first'   // Extensions in filenames begin after the first dot
        }
]
```

This allows me to generate multiple bundles matching the src pattern. This used to work in an earlier version. Is it not supported anymore?

**Comment by maiermic** [comment] 2015-01-29 08:38
I would appreciate a solution, too.

**Comment by AdrienGib** [comment] 2015-02-16 16:08
+1 ...

**Comment by tleunen** [comment] 2015-02-17 03:27
Hey @chrisjaure and @f03lipe, I'd like to take a look at this.. Do you have a test environment to share so I can start somewhere?

**Comment by chrisjaure** [comment] 2015-02-19 01:14
@tleunen Here's a basic setup: https://gist.github.com/chrisjaure/25af865ffb6561adca22

Run `grunt browserify:dist` to build it and `grunt browserify:watch` to watch it. While watching, make a change to and save `common.js` and check the contents of `second.min.js` to see that it hasn't been updated.

Thanks for looking into this.

**Comment by tragiclifestories** [comment] 2015-03-13 12:55
@tleunen Did you ever get anywhere with this?

**Comment by petersendidit** [comment] 2015-03-13 14:11
If you use the example in https://github.com/jmreidy/grunt-browserify/tree/master/examples/watch and use the 'browserifyWithWatch' task browserify will correctly watch multiple bundles.  Using `grunt-contrib-watch` as the keepAlive seems to work.

As some have noted the problem is that when you specify `keepAlive: true` browserify never calls the `next` function which would allow the next bundle to get updated. I don't see an easy way to fix this as grunt is handling the files and handing the browserify task one file at at time. Browserify never knows that there are multiple bundles. You would have to have some new task that does all the multiple bundle file handling so it knows to keep looping over the bundles.

**Comment by tleunen** [comment] 2015-03-13 14:13
Sorry I'm quite busy these days.. I'll be more available in 2 weeks and will be able to take a look.

**Comment by tleunen** [comment] 2015-03-23 17:38
I made a change in my fork. Could you test it a bit before I merge it in the main repo?
https://github.com/tleunen/grunt-browserify/tree/feature/multi-dest
You can use my fork by modifying your `package.json` file and changing the version of `grunt-browserify` to `tleunen/grunt-browserify#multi-dest`
The change is really minimal but I want to be sure nothing breaks.

**Comment by chrisjaure** [comment] 2015-03-23 21:02
@tleunen Looks like that did the trick! Thanks a bunch!

Some notes:
- The process died with a segfault once, but it looked like it was caused by watchify. Haven't been able to reproduce it again.
- Nitpick: it prints `>> Watchifying bundle <name>...` every time a change is detected and the bundle is updated, which gets a little noisy.
- Now that I don't have to use `grunt-contrib-watch`, processor usage is way down and rebundling is super quick, as expected :)

**Comment by tleunen** [comment] 2015-03-23 23:15
Before, it was printing `>> Watchifying...`. I added the bundle name so it's easier to know which one is ready. What do you suggest?
I'd like to keep a comment because it tells the user that the bundle is ready.

**Comment by chrisjaure** [comment] 2015-03-23 23:49
When a file changes, I see:
```
>> <file> changed, updating bundle.
>> File <bundle> created.
>> Watchifying bundle <bundle>...
```

Isn't it enough to show just the first two messages since it's implied the bundle is being watchified when the task is first run? But that's fine if you can't differentiate between first creation and subsequent creations. I can deal with a little extra noise :)

**Comment by tleunen** [comment] 2015-03-24 14:00
I merged the watchifying message with the bundle created message. Is it better? :)
So it's now:
```
>> <file> changed, updating bundle.
>> <bundle> created. Watchifying...
```

**Comment by chrisjaure** [comment] 2015-03-24 15:34
:+1:

**Closed** 2015-03-26 18:57 UTC
